services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: preflightchecklibs:latest
    # Use simliar naming pattern used in ImGui to include third party libraries
    volumes:
      - ${EXPORT_DIR:-./libs}:/mnt/export/libs
      - ${FONTS_DIR:-./third_party/fonts}:/mnt/export/fonts
    entrypoint: /entrypoint.sh
