services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: preflightchecklibs:latest
    volumes:
      - ${EXPORT_LIBS_DIR:-${EXPORT_BASE_DIR:-./third_party}/libs}:/mnt/export/libs
      - ${EXPORT_FONTS_DIR:-${EXPORT_BASE_DIR:-./third_party}/fonts}:/mnt/export/fonts
    entrypoint: /entrypoint.sh
